### ISSUE TITLE
With ssl dont work

### ISSUE THREAD

**Issue by proone600hp** [davidegiacometti/mabbix#1]
Hi i install mabbix and its work fine, but with ssl he dont work, can u help me pls
thx

**Comment by davidegiacometti** [comment]
Hi!
What's the version of Zabbix?
Are you using SSL on Mabbix, Zabbix or both?
Do you have any error in the web interface or in the web server log?

**Comment by dzoccarato** [comment]
Hi @proone600hp,
Thank you for using our Mabbix! :)

Have you try to enable Mabbix debug? You can enable it by set to "true" the DEBUG const definition in your configuration.php file.
After this you should find Mabbix's debug log file into tmp folder (also this is set in configuration.php)
Is the SSL a self-signed certificate?

Another step you can do is looking for error in browser console (tipically accessible with F12 func key): do you have some error here?

Best,
Davide

**Comment by proone600hp** [comment]
Hi @davidegiacometti 
Zabbix version 4.0 and 3.4
I use SSL on Zabbix
Yes, i have error "Couldn't contact API server. Check app config.json: incorrect baseurl or API server down.", but if i off SSL all work fine

**Comment by proone600hp** [comment]
Hi, @dzoccarato 
1) Debug on true, but he dont write log, /tmp folder empty
2) Yes, SSL a self-signed certificate
3) On console error (F12):  [https://ibb.co/fvqAdp](https://ibb.co/fvqAdp)

**Comment by dzoccarato** [comment]
Hi @proone600hp
Thanks for the details,

1. I'm sorry about the missing write of log file, could be missing write permission on tmp folder?

2. As the SSL certificate is a self-signed, the browser some time doesn't accept it because the authority is not trusted.
If you go to the network tab of console error (F12) you should find all network request.
I'm interested about xhr requests.
Could you look for the requested starting with mabbix base URL, copy the full URL of one of mabbix request, and past it in a browser's new tab?
If the browser doesn't accept the ssl, you should find a label such this "proceed anyway ...". In this way you force the brower to accept the SSL.
Then try to reload mabbix page.

3. I'm, but if you have attach a screenshot, I can't see it: the URL you provide us take me to GitHub issue page.

Best,
Davide

**Comment by dzoccarato** [comment]
Hi @proone600hp
Thanks for the details,

1. I'm sorry about the missing write of log file, could be missing write permission on tmp folder?

2. As the SSL certificate is a self-signed, the browser some time doesn't accept it because the authority is not trusted.
If you go to the network tab of console error (F12) you should find all network request.
I'm interested about xhr requests.
Could you look for the requested starting with mabbix base URL, copy the full URL of one of mabbix request, and past it in a browser's new tab?
If the browser doesn't accept the ssl, you should find a label such this "proceed anyway ...". In this way you force the brower to accept the SSL.
Then try to reload mabbix page.

If zabbix and mabbix are on the same server, this procedure should force the browser to trust also zabbix APIs URL

3. I'm sorry, but if you have attach a screenshot, I can't see it: the URL you provide us take me to GitHub issue page.

Best,
Davide

**Comment by proone600hp** [comment]
@dzoccarato  
Thx for replay.
I have error 
![image 104](https://user-images.githubusercontent.com/43769879/46594184-19972680-caf3-11e8-85df-7c2ffe095a00.png)
(ailed to load Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '' is therefore not allowed access.) and after install [Allow-Control-Allow-Origin: *](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi/related?utm_source=chrome-app-launcher-info-dialog) now i can enter to login page on mabbix but after i enter login and password now i have error "Peer's Certificate issuer is not recognized."

**Comment by proone600hp** [comment]
![image 105](https://user-images.githubusercontent.com/43769879/46601190-39881380-cb0e-11e8-9490-c697df01aa19.png)

after install Allow-Control-Allow-Origin: *
![image 106](https://user-images.githubusercontent.com/43769879/46601203-3db43100-cb0e-11e8-9538-c9dc15ce4e14.png)

**Comment by davidegiacometti** [comment]
Hi @proone600hp 
I have been able to test the application under SSL.
As far as I can understand you have two main issues related to the self-signed certificate.

1. Update the **baseUrl** in the file `/opt/mabbix/public/config.json` with the common name of the certificate (i.e. www.example.com) instead of the IP address. This will solve the error in the front-end.
2. In order to have the back-end fixed you need to configure the certificate as trusted in your server. Please refer to [this guide](https://leehblue.com/add-self-signed-cert-curl/).

Let me know if you have been able to fix the problem.

Davide

**Comment by proone600hp** [comment]
Hi @davidegiacometti 
1. That helped thx
2. i use centos 7 how i can do its for centos 7?

thx

**Comment by davidegiacometti** [comment]
Hi @proone600hp 
You should be able to add the certificate with the linked documentation.
The path `/usr/share/ca-certificates` may be different on CentOS.
If you can't find the correct path, try to google **Trust a Self-Signed Certificate in CentOS 7** and find a guide.

Davide

**Comment by proone600hp** [comment]
Hi @davidegiacometti yes i do it, but it dont help. We have corporate CA, i request certification (for zabbix) from  corp CA. I need put zabbix cert to /usr/share/ca-certificates or my corp CA cert ? Sry for my stupid questions :D  I have little experience with cert.

thx

**Comment by proone600hp** [comment]
@davidegiacometti  Ok, I changed the self-signed certificate to certificate issued by comodo, but else i have error "Peer's Certificate issuer is not recognized"

**Comment by davidegiacometti** [comment]
Hi,
/usr/share/ca-certificates is for CA certificates but you should also be able to trust your zabbix certificate.
With the comodo certificate are you having the error in the browser console? If you open zabbix do you have any warning related to the certificate near the URL bar?

**Comment by proone600hp** [comment]
@davidegiacometti there are no errors now (only on mabbix error "Peer's Certificate issuer is not recognized" ), url bar now green

**Comment by davidegiacometti** [comment]
I think there is something missing in your SSL configuration.
You can try to avoid SSL certificate check during CURL. Replace `mabbix/public/back-end/core/AbstractZabbix.php` with the attached one.

[AbstractZabbix.zip](https://github.com/davidegiacometti/mabbix/files/2465738/AbstractZabbix.zip)

**Comment by proone600hp** [comment]
Hi @davidegiacometti nice, now all works big thank you for you help, good job! So i tested it on Zabbix 4, CentOS 7, php 5.6 (on php 5.4 dont work), MySQL 5.4 all now good works.

**Comment by davidegiacometti** [comment]
Thank you @proone600hp
I close this issue since you have fixed the problem.
