### ISSUE TITLE
Time period not working

### ISSUE THREAD

**Issue by proone600hp** [davidegiacometti/mabbix#2]
Hi,
Time period not working, i change period 604800sec but he always give me 1h period on graph
![image](https://user-images.githubusercontent.com/43769879/47776191-00614e80-dd1c-11e8-9c85-f14f37506f2e.png)

thx.

**Comment by proone600hp** [comment]
Hi, can u help me pls?

**Comment by davidegiacometti** [comment]
Hi @proone600hp

This behavior is related to changes made to [this file](https://github.com/zabbix/zabbix/blob/trunk/frontends/php/chart2.php) in Zabbix 4.
This file is used to export the graphs in PNG from Zabbix.
Unfortunately, due to lack of time I am not working on this project anymore and support the version 4 will require a lot of work.

Regards,
Davide

**Comment by proone600hp** [comment]
ok, thank you
